// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"jan-server/mono/apps/backend/internal/domain"
	"jan-server/mono/apps/backend/internal/domain/apikey"
	"jan-server/mono/apps/backend/internal/domain/conversation"
	"jan-server/mono/apps/backend/internal/domain/document"
	"jan-server/mono/apps/backend/internal/domain/mcptool"
	"jan-server/mono/apps/backend/internal/domain/model"
	"jan-server/mono/apps/backend/internal/domain/modelprompttemplate"
	"jan-server/mono/apps/backend/internal/domain/project"
	"jan-server/mono/apps/backend/internal/domain/prompttemplate"
	"jan-server/mono/apps/backend/internal/domain/share"
	"jan-server/mono/apps/backend/internal/domain/tokenusage"
	"jan-server/mono/apps/backend/internal/domain/user"
	"jan-server/mono/apps/backend/internal/domain/usersettings"
	"jan-server/mono/apps/backend/internal/infrastructure"
	"jan-server/mono/apps/backend/internal/infrastructure/connector"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/apikeyrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/conversationrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/documentrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/mcptoolrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/modelprompttemplaterepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/modelrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/projectrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/prompttemplaterepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/sharerepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/tokenusagerepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/userrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/database/repository/usersettingsrepo"
	"jan-server/mono/apps/backend/internal/infrastructure/inference"
	"jan-server/mono/apps/backend/internal/infrastructure/logger"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/admin"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/apikeyhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/authhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/chathandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/connectorhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/conversationhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/documenthandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/guesthandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/imagehandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/mcptoolhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/messageshandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/modelhandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/modelprompthandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/projecthandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/prompttemplatehandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/sharehandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/usagehandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/handlers/usersettingshandler"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/auth"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/public"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1"
	admin2 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/admin"
	model3 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/admin/model"
	provider2 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/admin/provider"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/chat"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/connectors"
	conversation2 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/conversation"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/image"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/llm/documents"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/llm/projects"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/messages"
	model2 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/model"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/model/provider"
	share2 "jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/share"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/usage"
	"jan-server/mono/apps/backend/internal/interfaces/httpserver/routes/v1/users"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "net/http/pprof"
)

// Injectors from wire.go:

// InitializeHTTPServer creates a fully-wired HTTPServer with all dependencies.
// The cleanup function can be used to gracefully shutdown resources.
func InitializeHTTPServer() (*httpserver.HTTPServer, func(), error) {
	config, err := infrastructure.ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	zerologLogger := logger.GetLogger()
	db, err := infrastructure.ProvideDatabase(config, zerologLogger)
	if err != nil {
		return nil, nil, err
	}
	database := infrastructure.ProvideTransactionDatabase(db)
	providerRepository := modelrepo.NewProviderGormRepository(database)
	providerModelRepository := modelrepo.NewProviderModelGormRepository(database)
	modelCatalogRepository := modelrepo.NewModelCatalogGormRepository(database)
	providerModelService := model.NewProviderModelService(providerModelRepository, modelCatalogRepository)
	modelCatalogService := model.NewModelCatalogService(modelCatalogRepository)
	providerService := model.NewProviderService(providerRepository, providerModelService, modelCatalogService)
	modelHandler := modelhandler.NewModelHandler(providerService, providerModelService)
	modelCatalogHandler := modelhandler.NewModelCatalogHandler(modelCatalogService, providerModelService)
	modelProviderRoute := provider.NewModelProviderRoute(modelHandler)
	repository := userrepo.NewLocalUserRepository(db)
	serviceConfig := domain.ProvideUserServiceConfig(config)
	service := user.NewService(repository, serviceConfig)
	authHandler := authhandler.NewAuthHandler(service, zerologLogger)
	modelRoute := model2.NewModelRoute(modelHandler, modelCatalogHandler, modelProviderRoute, authHandler)
	inferenceProvider := inference.NewInferenceProvider(config)
	providerHandler := modelhandler.NewProviderHandler(providerService, providerModelService, inferenceProvider)
	conversationRepository := conversationrepo.NewConversationGormRepository(database)
	conversationService := conversation.NewConversationService(conversationRepository)
	messageActionService := conversation.NewMessageActionService(conversationRepository)
	projectRepository := projectrepo.NewProjectGormRepository(db)
	projectService := project.NewProjectService(projectRepository)
	shareRepository := sharerepo.NewShareGormRepository(database)
	conversationHandler := conversationhandler.NewConversationHandler(conversationService, messageActionService, projectService, shareRepository)
	processorConfig := domain.ProvidePromptProcessorConfig(config, zerologLogger)
	promptTemplateRepository := prompttemplaterepo.NewPromptTemplateGormRepository(database)
	prompttemplateService := prompttemplate.NewService(promptTemplateRepository)
	modelPromptTemplateRepository := modelprompttemplaterepo.NewModelPromptTemplateGormRepository(database)
	modelprompttemplateService := modelprompttemplate.NewService(modelPromptTemplateRepository, promptTemplateRepository)
	projectFileRepository := documentrepo.NewProjectFileGormRepository(db)
	documentContentRepository := documentrepo.NewDocumentContentGormRepository(db)
	projectFileService := document.NewProjectFileService(projectFileRepository, documentContentRepository)
	processorImpl := domain.ProvidePromptProcessor(processorConfig, zerologLogger, prompttemplateService, modelprompttemplateService, projectFileService)
	client := infrastructure.ProvideMemoryClient(config, zerologLogger)
	usersettingsRepository := usersettingsrepo.NewUserSettingsGormRepository(db)
	usersettingsService := usersettings.NewService(usersettingsRepository, modelHandler)
	memoryHandler := handlers.ProvideMemoryHandler(client, config, usersettingsService)
	tokenusageRepository := tokenusagerepo.NewTokenUsageGormRepository(db)
	tokenusageService := tokenusage.NewService(tokenusageRepository)
	documentService := document.NewDocumentService(documentContentRepository, projectFileRepository, config)
	chatHandler := chathandler.NewChatHandler(inferenceProvider, providerHandler, conversationHandler, conversationService, projectService, processorImpl, memoryHandler, usersettingsService, tokenusageService, documentService)
	chatCompletionRoute := chat.NewChatCompletionRoute(chatHandler, authHandler)
	chatRoute := chat.NewChatRoute(chatCompletionRoute)
	zImageService := inference.NewZImageService(config)
	mediaclientClient := infrastructure.ProvideMediaClient(config, zerologLogger)
	imageHandler := imagehandler.NewImageHandler(config, providerService, zImageService, mediaclientClient)
	imageRoute := image.NewImageRoute(imageHandler, authHandler)
	conversationRoute := conversation2.NewConversationRoute(conversationHandler, authHandler)
	branchHandler := conversationhandler.NewBranchHandler(conversationService, messageActionService, conversationRepository)
	branchRoute := conversation2.NewBranchRoute(conversationHandler, branchHandler, authHandler)
	projectHandler := projecthandler.NewProjectHandler(projectService)
	projectRoute := projects.NewProjectRoute(projectHandler, authHandler)
	providerModelHandler := modelhandler.NewProviderModelHandler(providerModelService, providerService, modelCatalogService)
	adminAuditLogger := infrastructure.ProvideAdminAuditLogger(db, zerologLogger)
	modelPromptTemplateHandler := modelprompthandler.NewModelPromptTemplateHandler(modelprompttemplateService, adminAuditLogger)
	adminModelRoute := model3.NewAdminModelRoute(modelHandler, modelCatalogHandler, providerModelHandler, modelPromptTemplateHandler)
	adminProviderRoute := provider2.NewAdminProviderRoute(providerHandler)
	keycloakClient := infrastructure.ProvideKeycloakClient(config, zerologLogger)
	adminUserHandler := admin.NewAdminUserHandler(keycloakClient, adminAuditLogger)
	adminGroupHandler := admin.NewAdminGroupHandler(keycloakClient, adminAuditLogger)
	featureFlagHandler := admin.NewFeatureFlagHandler(database, adminAuditLogger)
	promptTemplateHandler := prompttemplatehandler.NewPromptTemplateHandler(prompttemplateService, adminAuditLogger)
	mcpToolRepository := mcptoolrepo.NewMCPToolGormRepository(database)
	mcptoolService := mcptool.NewService(mcpToolRepository)
	mcpToolHandler := mcptoolhandler.NewMCPToolHandler(mcptoolService, adminAuditLogger)
	usageHandler := usagehandler.NewUsageHandler(tokenusageService)
	adminRoute := admin2.NewAdminRoute(adminModelRoute, adminProviderRoute, adminUserHandler, adminGroupHandler, featureFlagHandler, promptTemplateHandler, mcpToolHandler, usageHandler)
	userSettingsHandler := usersettingshandler.NewUserSettingsHandler(usersettingsService, providerService, config, zerologLogger)
	usersRoute := users.NewUsersRoute(userSettingsHandler, authHandler)
	itemRepository := conversationrepo.NewItemGormRepository(db)
	shareService := share.NewShareService(shareRepository, conversationRepository, itemRepository)
	shareHandler := sharehandler.NewShareHandler(shareService, conversationHandler, config)
	shareRoute := share2.NewShareRoute(shareHandler, authHandler, conversationHandler)
	publicShareRoute := public.NewPublicShareRoute(shareHandler)
	messagesHandler := messageshandler.NewMessagesHandler(inferenceProvider, providerHandler, conversationService)
	messagesRoute := messages.NewMessagesRoute(messagesHandler, authHandler)
	usageRoute := usage.NewUsageRoute(usageHandler, authHandler)
	documentOCRService := inference.NewDocumentOCRService(config)
	documentHandler := documenthandler.NewDocumentHandler(documentService, projectFileService, projectService, providerService, documentOCRService, mediaclientClient, config)
	documentRoute := documents.NewDocumentRoute(documentHandler, authHandler)
	tokenEncryptor, err := connector.ProvideTokenEncryptor(config)
	if err != nil {
		return nil, nil, err
	}
	oAuthProvider := connector.ProvideOAuthProvider(config)
	connectorService := connector.ProvideConnectorService(db, config, tokenEncryptor, oAuthProvider, zerologLogger)
	connectorHandler := connectorhandler.NewConnectorHandler(connectorService)
	connectorRoute := connectors.NewConnectorRoute(connectorHandler, authHandler)
	v1Route := v1.NewV1Route(modelRoute, chatRoute, imageRoute, conversationRoute, branchRoute, projectRoute, adminRoute, usersRoute, promptTemplateHandler, mcpToolHandler, shareRoute, publicShareRoute, messagesRoute, usageRoute, documentRoute, connectorRoute)
	guestHandler := guestauth.NewGuestHandler(keycloakClient, zerologLogger)
	upgradeHandler := guestauth.NewUpgradeHandler(keycloakClient, zerologLogger)
	tokenHandler := authhandler.NewTokenHandler(keycloakClient, zerologLogger)
	apikeyRepository := apikeyrepo.NewAPIKeyRepository(db)
	apikeyConfig := domain.ProvideAPIKeyConfig(config)
	apikeyService := apikey.NewService(apikeyRepository, repository, keycloakClient, apikeyConfig, zerologLogger)
	handler := apikeyhandler.NewHandler(apikeyService, zerologLogger)
	keycloakOAuthHandler := authhandler.ProvideKeycloakOAuthHandler(config)
	registerHandler := authhandler.NewRegisterHandler(keycloakClient, zerologLogger)
	authRoute := auth.NewAuthRoute(guestHandler, upgradeHandler, tokenHandler, handler, authHandler, keycloakOAuthHandler, registerHandler)
	keycloakValidator, err := infrastructure.ProvideKeycloakValidator(config, zerologLogger)
	if err != nil {
		return nil, nil, err
	}
	infrastructureInfrastructure := infrastructure.NewInfrastructure(db, keycloakValidator, zerologLogger)
	tracker := infrastructure.ProvideAnalyticsTracker(config, zerologLogger)
	httpServer := httpserver.NewHttpServer(v1Route, authRoute, infrastructureInfrastructure, config, apikeyService, tracker)
	return httpServer, func() {
	}, nil
}
