// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	logger2 "gorm.io/gorm/logger"
	"jan-server/services/response-api/internal/config"
	"jan-server/services/response-api/internal/domain/agent"
	"jan-server/services/response-api/internal/domain/agent/planners"
	deepresearch "jan-server/services/response-api/internal/domain/agent/planners/deep_research"
	docplanner "jan-server/services/response-api/internal/domain/agent/planners/doc"
	pdfplanner "jan-server/services/response-api/internal/domain/agent/planners/pdf"
	skillexec "jan-server/services/response-api/internal/domain/agent/planners/skill"
	"jan-server/services/response-api/internal/domain/agent/planners/slide_creator"
	spreadsheetplanner "jan-server/services/response-api/internal/domain/agent/planners/spreadsheet"
	artifact2 "jan-server/services/response-api/internal/domain/artifact"
	conversation2 "jan-server/services/response-api/internal/domain/conversation"
	"jan-server/services/response-api/internal/domain/llm"
	plan2 "jan-server/services/response-api/internal/domain/plan"
	response2 "jan-server/services/response-api/internal/domain/response"
	"jan-server/services/response-api/internal/domain/skill"
	"jan-server/services/response-api/internal/domain/tool"
	"jan-server/services/response-api/internal/infrastructure/apikey"
	"jan-server/services/response-api/internal/infrastructure/auth"
	"jan-server/services/response-api/internal/infrastructure/database"
	"jan-server/services/response-api/internal/infrastructure/llmprovider"
	"jan-server/services/response-api/internal/infrastructure/logger"
	"jan-server/services/response-api/internal/infrastructure/mcp"
	"jan-server/services/response-api/internal/infrastructure/media"
	"jan-server/services/response-api/internal/infrastructure/repository/artifact"
	"jan-server/services/response-api/internal/infrastructure/repository/conversation"
	"jan-server/services/response-api/internal/infrastructure/repository/plan"
	"jan-server/services/response-api/internal/infrastructure/repository/response"
	skill2 "jan-server/services/response-api/internal/infrastructure/skill"
	"jan-server/services/response-api/internal/interfaces/httpserver"
	"jan-server/services/response-api/internal/webhook"
)

// Injectors from wire.go:

// BuildApplication demonstrates how to assemble the response service with Wire.
func BuildApplication(ctx context.Context) (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.New(configConfig)
	databaseConfig := newDatabaseConfig(configConfig)
	db, err := newGormDB(ctx, databaseConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	postgresRepository := response.NewPostgresRepository(db)
	repository := conversation.NewRepository(db)
	itemRepository := conversation.NewItemRepository(db)
	client := newLLMProvider(configConfig)
	mcpClient := newMCPClient(configConfig)
	orchestrator := newOrchestrator(configConfig, client, mcpClient)
	planPostgresRepository := plan.NewPostgresRepository(db)
	service := plan2.NewService(planPostgresRepository)
	artifactPostgresRepository := artifact.NewPostgresRepository(db)
	artifactService := artifact2.NewService(artifactPostgresRepository)
	mediaClient := newMediaClient(configConfig)
	skillService, err := newSkillService()
	if err != nil {
		return nil, err
	}
	registry := newAgentRegistry(service, mcpClient, client, artifactService, configConfig, mediaClient, skillService)
	agentOrchestrator := newAgentOrchestrator(registry, service)
	httpService := newWebhookService(zerologLogger)
	responseService := newResponseService(postgresRepository, repository, itemRepository, postgresRepository, orchestrator, agentOrchestrator, mcpClient, mediaClient, client, httpService, registry, service, zerologLogger)
	apikeyClient := newAPIKeyProvider(configConfig)
	validator, err := newAuthValidator(ctx, configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(configConfig, zerologLogger, responseService, service, artifactService, apikeyClient, validator)
	application := NewApplication(httpServer, zerologLogger)
	return application, nil
}

// wire.go:

var responseSet = wire.NewSet(response.NewPostgresRepository, wire.Bind(new(response2.Repository), new(*response.PostgresRepository)), wire.Bind(new(response2.ToolExecutionRepository), new(*response.PostgresRepository)), plan.NewPostgresRepository, wire.Bind(new(plan2.Repository), new(*plan.PostgresRepository)), artifact.NewPostgresRepository, wire.Bind(new(artifact2.Repository), new(*artifact.PostgresRepository)), conversation.NewRepository, wire.Bind(new(conversation2.Repository), new(*conversation.Repository)), conversation.NewItemRepository, wire.Bind(new(conversation2.ItemRepository), new(*conversation.ItemRepository)), newLLMProvider, wire.Bind(new(llm.Provider), new(*llmprovider.Client)), wire.Bind(new(llm.ModelInfoProvider), new(*llmprovider.Client)), newMCPClient, wire.Bind(new(tool.MCPClient), new(*mcp.Client)), wire.Bind(new(planners.MCPClient), new(*mcp.Client)), newMediaClient,
	newSkillService, wire.Bind(new(skill.Service), new(*skill2.Service)), newOrchestrator,
	newAgentOrchestrator,
	newWebhookService, wire.Bind(new(webhook.Service), new(*webhook.HTTPService)), newAPIKeyProvider, wire.Bind(new(apikey.Provider), new(*apikey.Client)), plan2.NewService, newAgentRegistry,
	newResponseService, artifact2.NewService,
)

func newDatabaseConfig(cfg *config.Config) database.Config {
	return database.Config{
		DSN:             cfg.GetDatabaseWriteDSN(),
		MaxIdleConns:    cfg.DBMaxIdleConns,
		MaxOpenConns:    cfg.DBMaxOpenConns,
		ConnMaxLifetime: cfg.DBConnLifetime,
		LogLevel:        logger2.Warn,
	}
}

func newGormDB(ctx context.Context, cfg database.Config, log zerolog.Logger) (*gorm.DB, error) {
	db, err := database.Connect(cfg)
	if err != nil {
		return nil, err
	}
	if err := database.AutoMigrate(ctx, db, log); err != nil {
		return nil, err
	}
	return db, nil
}

func newAuthValidator(ctx context.Context, cfg *config.Config, log zerolog.Logger) (*auth.Validator, error) {
	return auth.NewValidator(ctx, cfg, log)
}

func newLLMProvider(cfg *config.Config) *llmprovider.Client {
	return llmprovider.NewClient(cfg.LLMAPIURL)
}

func newMCPClient(cfg *config.Config) *mcp.Client {
	return mcp.NewClient(cfg.MCPToolsURL)
}

func newAPIKeyProvider(cfg *config.Config) *apikey.Client {
	return apikey.NewClient(cfg.LLMAPIURL)
}

func newMediaClient(cfg *config.Config) *media.Client {
	return media.NewClient(cfg.MediaAPIURL)
}

func newSkillService() (*skill2.Service, error) {
	return skill2.NewService()
}

func newOrchestrator(cfg *config.Config, provider llm.Provider, mcpClient tool.MCPClient) *tool.Orchestrator {
	return tool.NewOrchestrator(provider, mcpClient, cfg.MaxToolDepth, cfg.ToolTimeout, cfg.LLMStreamMode)
}

func newAgentOrchestrator(registry agent.Registry, planService plan2.Service) agent.Orchestrator {
	return agent.NewOrchestrator(registry, planService)
}

func newWebhookService(log zerolog.Logger) *webhook.HTTPService {
	return webhook.NewHTTPService(log)
}

func newAgentRegistry(planService plan2.Service, mcpClient tool.MCPClient, llmProvider llm.Provider, artifactService artifact2.Service, cfg *config.Config, mediaClient *media.Client, skillService skill.Service) agent.Registry {
	registry := agent.NewRegistry()

	deepResearchPlanner := deepresearch.NewPlanner(planService)
	if err := registry.RegisterPlanner(deepResearchPlanner); err != nil {

		_ = err
	}

	slideCreatorPlanner := slide_creator.NewSlideCreatorPlanner(planService, artifactService)
	if err := registry.RegisterPlanner(slideCreatorPlanner); err != nil {
		_ = err
	}

	docGeneratorPlanner := docplanner.NewPlanner(planService, artifactService)
	if err := registry.RegisterPlanner(docGeneratorPlanner); err != nil {
		_ = err
	}

	pdfGeneratorPlanner := pdfplanner.NewPlanner(planService, artifactService)
	if err := registry.RegisterPlanner(pdfGeneratorPlanner); err != nil {
		_ = err
	}

	spreadsheetGeneratorPlanner := spreadsheetplanner.NewPlanner(planService, artifactService)
	if err := registry.RegisterPlanner(spreadsheetGeneratorPlanner); err != nil {
		_ = err
	}

	codeFixer := llm.NewCodeFixer(llmProvider, cfg.CodeFixModel)
	codeFixer.SetDisableCustomTemperature(cfg.LLMDisableCustomTemperature)

	deepResearchExecutor := deepresearch.NewExecutor(mcpClient, codeFixer)

	skillExecutor := skillexec.NewExecutor(
		mcpClient,
		codeFixer,
		skillService,
		cfg.SkillExecutionEnabled,
		cfg.SkillMaxInstallRetries,
		cfg.SkillMaxCodeFixRetries,
		cfg.SkillMaxFileSize,
		cfg.SkillExecutionTimeout,
		map[skill.SkillType]bool{skill.SkillTypeSlides: cfg.SkillSlidesEnabled, skill.SkillTypeDocs: cfg.SkillDocsEnabled, skill.SkillTypePDFs: cfg.SkillPDFsEnabled, skill.SkillTypeSpreadsheets: cfg.SkillSpreadsheetsEnabled},
	)
	slideCreatorExecutor := slide_creator.NewSlideCreatorExecutor(mcpClient, codeFixer, artifactService, mediaClient, cfg)
	routingExecutor := planners.NewRoutingExecutor(deepResearchExecutor, slideCreatorExecutor)
	artifactRoutingExecutor := planners.NewRoutingExecutor(slideCreatorExecutor, slideCreatorExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeToolCall, routingExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeLLMCall, routingExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeArtifactCreate, artifactRoutingExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeTransform, slideCreatorExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeSkillExecute, skillExecutor)

	return registry
}

func newResponseService(
	repo response2.Repository,
	conversations conversation2.Repository,
	conversationItems conversation2.ItemRepository,
	toolRepo response2.ToolExecutionRepository,
	orchestrator *tool.Orchestrator,
	agentOrchestrator agent.Orchestrator,
	mcpClient tool.MCPClient,
	mediaClient *media.Client,
	modelInfoProvider llm.ModelInfoProvider,
	webhookService webhook.Service,
	agentRegistry agent.Registry,
	planService plan2.Service,
	log zerolog.Logger,
) response2.Service {
	return response2.NewService(repo, conversations, conversationItems, toolRepo, orchestrator, agentOrchestrator, mcpClient, mediaClient, modelInfoProvider, webhookService, agentRegistry, planService, log)
}
