// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"jan-server/services/response-api/internal/config"
	"jan-server/services/response-api/internal/domain/agent"
	"jan-server/services/response-api/internal/domain/agent/planners"
	artifact2 "jan-server/services/response-api/internal/domain/artifact"
	conversation2 "jan-server/services/response-api/internal/domain/conversation"
	"jan-server/services/response-api/internal/domain/llm"
	plan2 "jan-server/services/response-api/internal/domain/plan"
	response2 "jan-server/services/response-api/internal/domain/response"
	"jan-server/services/response-api/internal/domain/tool"
	"jan-server/services/response-api/internal/infrastructure/apikey"
	"jan-server/services/response-api/internal/infrastructure/auth"
	"jan-server/services/response-api/internal/infrastructure/database"
	"jan-server/services/response-api/internal/infrastructure/llmprovider"
	"jan-server/services/response-api/internal/infrastructure/logger"
	"jan-server/services/response-api/internal/infrastructure/mcp"
	"jan-server/services/response-api/internal/infrastructure/media"
	"jan-server/services/response-api/internal/infrastructure/repository/artifact"
	"jan-server/services/response-api/internal/infrastructure/repository/conversation"
	"jan-server/services/response-api/internal/infrastructure/repository/plan"
	"jan-server/services/response-api/internal/infrastructure/repository/response"
	"jan-server/services/response-api/internal/interfaces/httpserver"
	"jan-server/services/response-api/internal/webhook"

	"github.com/google/wire"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	logger2 "gorm.io/gorm/logger"
)

// Injectors from wire.go:

// BuildApplication demonstrates how to assemble the response service with Wire.
func BuildApplication(ctx context.Context) (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.New(configConfig)
	databaseConfig := newDatabaseConfig(configConfig)
	db, err := newGormDB(ctx, databaseConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	postgresRepository := response.NewPostgresRepository(db)
	repository := conversation.NewRepository(db)
	itemRepository := conversation.NewItemRepository(db)
	client := newLLMProvider(configConfig)
	mcpClient := newMCPClient(configConfig)
	mediaClient := newMediaClient(configConfig)
	orchestrator := newOrchestrator(configConfig, client, mcpClient)
	httpService := newWebhookService(zerologLogger)
	planPostgresRepository := plan.NewPostgresRepository(db)
	service := plan2.NewService(planPostgresRepository)
	artifactPostgresRepository := artifact.NewPostgresRepository(db)
	artifactService := artifact2.NewService(artifactPostgresRepository)
	registry := newAgentRegistry(service, mcpClient, client, artifactService, configConfig, mediaClient)
	orchestrator2 := newAgentOrchestrator(registry, service)
	responseService := newResponseService(postgresRepository, repository, itemRepository, postgresRepository, orchestrator, orchestrator2, mcpClient, mediaClient, client, httpService, registry, service, zerologLogger)
	apiKeyProvider := newAPIKeyProvider(configConfig)
	validator, err := newAuthValidator(ctx, configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(configConfig, zerologLogger, responseService, service, artifactService, apiKeyProvider, validator)
	application := NewApplication(httpServer, zerologLogger)
	return application, nil
}

// wire.go:

var responseSet = wire.NewSet(response.NewPostgresRepository, wire.Bind(new(response2.Repository), new(*response.PostgresRepository)), wire.Bind(new(response2.ToolExecutionRepository), new(*response.PostgresRepository)), plan.NewPostgresRepository, wire.Bind(new(plan2.Repository), new(*plan.PostgresRepository)), artifact.NewPostgresRepository, wire.Bind(new(artifact2.Repository), new(*artifact.PostgresRepository)), conversation.NewRepository, wire.Bind(new(conversation2.Repository), new(*conversation.Repository)), conversation.NewItemRepository, wire.Bind(new(conversation2.ItemRepository), new(*conversation.ItemRepository)), newLLMProvider, wire.Bind(new(llm.Provider), new(*llmprovider.Client)), wire.Bind(new(llm.ModelInfoProvider), new(*llmprovider.Client)), newMCPClient, wire.Bind(new(tool.MCPClient), new(*mcp.Client)), wire.Bind(new(planners.MCPClient), new(*mcp.Client)), newMediaClient, newOrchestrator,
	newAgentOrchestrator, newWebhookService, wire.Bind(new(webhook.Service), new(*webhook.HTTPService)), plan2.NewService, newAgentRegistry,
	newResponseService, artifact2.NewService,
)

func newDatabaseConfig(cfg *config.Config) database.Config {
	return database.Config{
		DSN:             cfg.GetDatabaseWriteDSN(),
		MaxIdleConns:    cfg.DBMaxIdleConns,
		MaxOpenConns:    cfg.DBMaxOpenConns,
		ConnMaxLifetime: cfg.DBConnLifetime,
		LogLevel:        logger2.Warn,
	}
}

func newGormDB(ctx context.Context, cfg database.Config, log zerolog.Logger) (*gorm.DB, error) {
	db, err := database.Connect(cfg)
	if err != nil {
		return nil, err
	}
	if err := database.AutoMigrate(ctx, db, log); err != nil {
		return nil, err
	}
	return db, nil
}

func newAuthValidator(ctx context.Context, cfg *config.Config, log zerolog.Logger) (*auth.Validator, error) {
	return auth.NewValidator(ctx, cfg, log)
}

func newLLMProvider(cfg *config.Config) *llmprovider.Client {
	return llmprovider.NewClient(cfg.LLMAPIURL)
}

func newAPIKeyProvider(cfg *config.Config) *apikey.Client {
	return apikey.NewClient(cfg.LLMAPIURL)
}

func newMCPClient(cfg *config.Config) *mcp.Client {
	return mcp.NewClient(cfg.MCPToolsURL)
}

func newMediaClient(cfg *config.Config) *media.Client {
	return media.NewClient(cfg.MediaAPIURL)
}

func newOrchestrator(cfg *config.Config, provider llm.Provider, mcpClient tool.MCPClient) *tool.Orchestrator {
	return tool.NewOrchestrator(provider, mcpClient, cfg.MaxToolDepth, cfg.ToolTimeout)
}

func newAgentOrchestrator(registry agent.Registry, planService plan2.Service) agent.Orchestrator {
	return agent.NewOrchestrator(registry, planService)
}

func newWebhookService(log zerolog.Logger) *webhook.HTTPService {
	return webhook.NewHTTPService(log)
}

func newAgentRegistry(planService plan2.Service, mcpClient tool.MCPClient, llmProvider llm.Provider, artifactService artifact2.Service, cfg *config.Config, mediaClient *media.Client) agent.Registry {
	registry := agent.NewRegistry()

	deepResearchPlanner := planners.NewDeepResearchPlanner(planService)
	if err := registry.RegisterPlanner(deepResearchPlanner); err != nil {
		_ = err
	}

	// Register the slide generator planner
	slideGeneratorPlanner := planners.NewSlideGeneratorPlanner(planService, artifactService)
	if err := registry.RegisterPlanner(slideGeneratorPlanner); err != nil {
		_ = err
	}

	// Create code fixer for LLM-based code fix retry
	codeFixer := llm.NewCodeFixer(llmProvider, cfg.CodeFixModel)

	deepResearchExecutor := planners.NewDeepResearchExecutor(mcpClient, codeFixer)
	_ = registry.RegisterExecutor(plan2.ActionTypeToolCall, deepResearchExecutor)
	_ = registry.RegisterExecutor(plan2.ActionTypeLLMCall, deepResearchExecutor)

	// Register the slide generator executor for artifact creation
	slideGeneratorExecutor := planners.NewSlideGeneratorExecutor(mcpClient, codeFixer, artifactService, mediaClient)
	_ = registry.RegisterExecutor(plan2.ActionTypeArtifactCreate, slideGeneratorExecutor)

	return registry
}

func newResponseService(
	repo response2.Repository,
	conversations conversation2.Repository,
	conversationItems conversation2.ItemRepository,
	toolRepo response2.ToolExecutionRepository,
	orchestrator *tool.Orchestrator,
	agentOrchestrator agent.Orchestrator,
	mcpClient tool.MCPClient,
	mediaClient *media.Client,
	modelInfoProvider llm.ModelInfoProvider,
	webhookService webhook.Service,
	agentRegistry agent.Registry,
	planService plan2.Service,
	log zerolog.Logger,
) response2.Service {
	return response2.NewService(repo, conversations, conversationItems, toolRepo, orchestrator, agentOrchestrator, mcpClient, mediaClient, modelInfoProvider, webhookService, agentRegistry, planService, log)
}
